---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deployment strategy.
# This setup is supposed to be used with `docker-swarm`.
# See `./docs/pages/template/production.rst` docs.

version: "3.8"
services:  
  nginx:
    container_name: nginx
    dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    env_file: ./config/.env
    volumes:
      # Django's static files
      - django-static:/var/www/django/static
      - django-media:/var/www/django/media
      # Nginx config
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    # environment:
    #   - DOMAIN_NAME=./config/.env.DOMAIN_NAME
    depends_on:
      - web
    networks:
      - proxynet
  web:
    <<: &web
      # Image for production:
      container_name: "marketplace.services"
      build:
        target: production_build
        args:
          DJANGO_ENV: production

      restart: unless-stopped
      volumes:
        - django-media:/var/www/django/media  # since in dev it is app's folder
        - django-locale:/code/locale  # since in dev it is app's folder

    command: bash ./docker/django/gunicorn.sh
    networks:
      - proxynet
    expose:
      - 8000

# This task is an example of how to extend existing ones:
#   some_worker:
#     <<: *web
#     command: python manage.py worker_process
#     deploy:
#       replicas: 2

networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:

volumes:
  django-media:
  django-locale: