---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deployment strategy.
# This setup is supposed to be used with `docker-swarm`.
# See `./docs/pages/template/production.rst` docs.

version: "3.8"
services:  
  web:
    <<: &web
      # Image for production:
      container_name: "marketplace.services"
      build:
        target: production_build
        args:
          DJANGO_ENV: production

      restart: unless-stopped
      volumes:
        - django-media:/var/www/django/media  # since in dev it is app's folder
        - django-locale:/code/locale  # since in dev it is app's folder

    command: bash ./docker/django/gunicorn.sh
    networks:
      - proxynet
    expose:
      - 8000
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/docker/Dockerfile
    restart: unless-stopped
    env_file: ./config/.env
    volumes:
      # Django's static files
      - django-static:/var/www/django/static
      - django-media:/var/www/django/media
      # Nginx config
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "433:433"
    depends_on:
      - web
    networks:
      - proxynet

networks:
  proxynet:

volumes:
  django-media:
  django-locale: